### ISSUE TITLE
Plugin Usage

### ISSUE THREAD

**Issue by KalenAnson** [eBookArchitects/Incrementor#2]
I have installed this plugin via the Package Control plugin on both Sublime Text 2 & 3 on both Windows 7 and Mac OS X. The package appears to be installed when I browse my list of installed packages. I have restarted Sublime Text after installing the plugin.

However when I bring up the "find and replace" dialog and do a regex search for something, i.e. ([0-9]+) and attempt to use the "\i" as the replacement the plugin does not appear to be doing anything. What is going on here. Am I doing something wrong?
The documentation leads me to believe that I can simply insert \i as the replace and the plugin will then follow its documented behavior on that set of replacements.

Also the Mac keyboard shortcut on the documentation appears to be wrong. The find and replace is not "Super + G" or "Super + R" it defaults to "Command + Option + R".

**Comment by Cooperdale** [comment]
I loved this plugin to no end, but I can't seem to make it work with Sublime 3. It seemed to work for a while, then stopped.

**Comment by jstallent** [comment]
@Cooperdale Another developer updated the plugin for Sublime Text 3. You can get it here: https://github.com/born2c0de/Incrementor

**Comment by mglinski** [comment]
Hail Hydra!

**Comment by Cooperdale** [comment]
@jstallent You made my day, thanks.

**Comment by atroia** [comment]
If you're looking for a Mac compatible version, here's a link to my fork with added Mac shortcuts

https://github.com/atroia/Incrementor
